name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          root_file: systems/resume.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: systems/resume.pdf
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          SINGLE_COMMIT: true
          FOLDER: .
          GIT_CONFIG_NAME: Swebert Correa
          GIT_CONFIG_EMAIL: correaswebert@gmail.com
